### ISSUE TITLE
FullExport Job example not working for Items on Talend Studio 7.3

### ISSUE THREAD

**Issue by danieldefrancisco-lr** [openpim/talend#1]
After importing the fullExport job included in the examples https://www.openpim.org/talend/export-import.zip , If I activate the "Items" subJob and then run the job, I get this error:

```
Exception in component PIMInput_3 (fullExport)
java.lang.RuntimeException: {"errors":[{"message":"Fragment cannot be spread here as objects of type \"SearchResponse\" can never be of type \"ItemsResponse\"."}]}
	at com.vpedak.talend.components.source.Utils.getJson(Utils.java:43)
	at com.vpedak.talend.components.source.MyBufferizedProducerSupport$1.get(MyBufferizedProducerSupport.java:35)
	at com.vpedak.talend.components.source.MyBufferizedProducerSupport$1.get(MyBufferizedProducerSupport.java:1)
	at org.talend.sdk.component.api.base.BufferizedProducerSupport.next(BufferizedProducerSupport.java:34)
	at com.vpedak.talend.components.source.PIMInputSource.next(PIMInputSource.java:69)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.talend.sdk.component.runtime.base.LifecycleImpl.doInvoke(LifecycleImpl.java:65)
	at org.talend.sdk.component.runtime.input.InputImpl.readNext(InputImpl.java:82)
	at org.talend.sdk.component.runtime.input.InputImpl.next(InputImpl.java:64)
	at org.talend.sdk.component.runtime.manager.chain.ChainedInput.next(ChainedInput.java:39)
	at local_project.fullexport_0_1.fullExport.PIMInput_3Process(fullExport.java:4076)
	at local_project.fullexport_0_1.fullExport.PIMInput_2Process(fullExport.java:3148)
	at local_project.fullexport_0_1.fullExport.PIMInput_1Process(fullExport.java:1923)
	at local_project.fullexport_0_1.fullExport.runJobInTOS(fullExport.java:11828)
	at local_project.fullexport_0_1.fullExport.main(fullExport.java:11657)
```

**Comment by openpim** [comment]
Hi Daniel,

We will take a look today or tomorrow.

Thanks,
Slava Pedak

**Comment by openpim** [comment]
Hi Daniel,

It looks like you are using old version of Talend components. Can you please make the following:
1. stop Talend
2. delete directory **[DIRECTORY WHERE Talend IS INSTALLED]**\configuration\.m2\repository\com\vpedak
3. download components from https://www.openpim.org/talend/pim-components.car
4. install components again "java -jar pim-components.car studio-deploy **[DIRECTORY WHERE Talend IS INSTALLED]**"
5. try new components

Also if you want we can arrange a Google Meet call where we can show you Talend integration in more details and we can share your screen and try to resolve the issue on your side (if you still have it). Just drop me an email at team@openpim.org and we will organize a call.

Thanks,
Slava Pedak

**Comment by danieldefrancisco-lr** [comment]
Hi Slava,

Thanks a lot for the support.
I will try first following your instructions, and I will let you know.

Best regards

**Comment by danieldefrancisco-lr** [comment]
Hi!
I can confirm that , after refreshing the Talend components, it is working now.
So far I am just testing, so no call is needed yet.
Thanks again for your help.
